-- Flyway schema migration for Datapillar Studio

CREATE TABLE tenants (
  id BIGINT PRIMARY KEY COMMENT 'Tenant ID (Snowflake ID)',
  code VARCHAR(64) NOT NULL COMMENT 'Tenant Code',
  name VARCHAR(128) NOT NULL COMMENT 'Tenant Name',
  type VARCHAR(32) NOT NULL COMMENT 'Tenant Type',
  encrypt_public_key TEXT NULL COMMENT 'Tenant public key (generated by auth)',
  status TINYINT NOT NULL DEFAULT 1 COMMENT 'Status: 1 active, 0 disabled',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  UNIQUE KEY uq_tenant_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Tenant';

CREATE TABLE users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'User ID',
  tenant_id BIGINT NOT NULL COMMENT 'Primary Tenant ID (default tenant)',
  username VARCHAR(64) NOT NULL COMMENT 'Username',
  password VARCHAR(255) NOT NULL COMMENT 'Password hash',
  nickname VARCHAR(64) NULL COMMENT 'Nickname',
  email VARCHAR(128) NULL COMMENT 'Email',
  phone VARCHAR(32) NULL COMMENT 'Phone number',
  level INT NOT NULL DEFAULT 100 COMMENT 'User level (smaller value means higher privilege)',
  status TINYINT NOT NULL DEFAULT 1 COMMENT 'Status: 1 enabled, 0 disabled',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete: 0 no, 1 yes',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  UNIQUE KEY uq_user_username (username),
  UNIQUE KEY uq_user_email (email),
  KEY idx_user_tenant (tenant_id),
  CONSTRAINT fk_user_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='User (global identity; tenant_id is primary tenant)';

CREATE TABLE system_bootstrap (
  id TINYINT NOT NULL COMMENT 'Fixed single-row ID, value = 1',
  status TINYINT NOT NULL DEFAULT 0 COMMENT 'Bootstrap status: 0 pending, 1 provisioning, 2 failed, 3 completed',
  setup_tenant_id BIGINT NULL COMMENT 'Initial created first tenant ID',
  setup_admin_user_id BIGINT NULL COMMENT 'Initial created admin user ID',
  setup_token_hash VARCHAR(64) NULL COMMENT 'Setup wizard token hash (SHA-256)',
  setup_token_generated_at DATETIME NULL COMMENT 'Setup wizard token generated time',
  setup_completed_at DATETIME NULL COMMENT 'Bootstrap completed time',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='System bootstrap status';

INSERT INTO system_bootstrap (id, status)
VALUES (1, 0);

CREATE TABLE tenant_users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  user_id BIGINT NOT NULL COMMENT 'User ID',
  status TINYINT NOT NULL DEFAULT 1 COMMENT 'Status: 1 enabled, 0 disabled',
  is_default TINYINT NOT NULL DEFAULT 0 COMMENT 'Is default tenant',
  joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Joined At',
  UNIQUE KEY uq_tenant_user (tenant_id, user_id),
  KEY idx_tu_user (user_id),
  CONSTRAINT fk_tu_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_tu_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Tenant membership relation';

CREATE TABLE user_identities (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key ID',
  user_id BIGINT NOT NULL COMMENT 'User ID',
  issuer VARCHAR(255) NOT NULL COMMENT 'OIDC issuer (iss)',
  subject VARCHAR(128) NOT NULL COMMENT 'OIDC subject (sub)',
  identity_key CHAR(64) NOT NULL COMMENT 'SHA-256(issuer + "\\n" + subject)',
  username_snapshot VARCHAR(128) NULL COMMENT 'preferred_username snapshot',
  email_snapshot VARCHAR(128) NULL COMMENT 'email snapshot',
  profile_json JSON NULL COMMENT 'Optional raw IdP profile payload',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  UNIQUE KEY uq_user_identity_issuer_subject (issuer, subject),
  UNIQUE KEY uq_user_identity_key (identity_key),
  KEY idx_user_identity_user (user_id),
  CONSTRAINT fk_user_identity_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Global IdP principal to local user mapping';

CREATE TABLE tenant_sso_configs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  provider VARCHAR(32) NOT NULL COMMENT 'SSO provider: currently only dingtalk',
  status TINYINT NOT NULL DEFAULT 1 COMMENT 'Status: 1 enabled, 0 disabled',
  base_url VARCHAR(255) NULL COMMENT 'Open platform base URL/environment (optional)',
  config_json JSON NOT NULL COMMENT 'SSO config JSON',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  UNIQUE KEY uq_tenant_sso (tenant_id, provider),
  KEY idx_tenant_sso_tenant (tenant_id),
  CONSTRAINT fk_tenant_sso_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Tenant SSO configuration';

CREATE TABLE tenant_api_keys (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  name VARCHAR(64) NOT NULL COMMENT 'API key name',
  description VARCHAR(255) NULL COMMENT 'API key description',
  key_hash CHAR(64) NOT NULL COMMENT 'SHA-256 hash of API key',
  last_four CHAR(4) NOT NULL COMMENT 'Last 4 chars for display',
  status TINYINT NOT NULL DEFAULT 1 COMMENT 'Status: 1 active, 0 disabled',
  expires_at DATETIME NULL COMMENT 'Expiration time, NULL means never expires',
  last_used_at DATETIME NULL COMMENT 'Last used time',
  last_used_ip VARCHAR(64) NULL COMMENT 'Last used client IP',
  created_by BIGINT NOT NULL COMMENT 'Created by user ID',
  disabled_by BIGINT NULL COMMENT 'Disabled by user ID',
  disabled_at DATETIME NULL COMMENT 'Disabled at',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  UNIQUE KEY uq_tenant_api_key_hash (key_hash),
  UNIQUE KEY uq_tenant_api_key_name (tenant_id, name),
  KEY idx_tenant_api_key_status (tenant_id, status),
  KEY idx_tenant_api_key_last_used (tenant_id, last_used_at),
  CONSTRAINT fk_tenant_api_key_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_tenant_api_key_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_tenant_api_key_disabled_by FOREIGN KEY (disabled_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Tenant API keys';

-- =========================
-- Permission/menu dictionary (global shared)
-- =========================
CREATE TABLE permissions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Permission ID',
  code VARCHAR(32) NOT NULL COMMENT 'Permission Code',
  name VARCHAR(64) NOT NULL COMMENT 'Permission Name',
  description VARCHAR(255) NULL COMMENT 'Permission Description',
  level INT NOT NULL DEFAULT 0 COMMENT 'Permission level (larger value means higher privilege)',
  sort INT NOT NULL DEFAULT 0 COMMENT 'Sort Order',
  status TINYINT NOT NULL DEFAULT 1 COMMENT 'Status: 1 enabled, 0 disabled',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  UNIQUE KEY uq_permission_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Permission set (global dictionary)';

CREATE TABLE feature_object_categories (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Category ID',
  code VARCHAR(64) NOT NULL COMMENT 'Category Code',
  name VARCHAR(64) NOT NULL COMMENT 'Category Name',
  description VARCHAR(255) NULL COMMENT 'Category Description',
  sort INT NOT NULL DEFAULT 0 COMMENT 'Sort Order',
  status TINYINT NOT NULL DEFAULT 1 COMMENT 'Status: 1 enabled, 0 disabled',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  UNIQUE KEY uq_feature_category_code (code),
  UNIQUE KEY uq_feature_category_name (name),
  KEY idx_feature_category_sort (sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Feature object category';

CREATE TABLE feature_objects (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Object ID',
  parent_id BIGINT NULL COMMENT 'Parent Object ID',
  type ENUM('MENU','PAGE') NOT NULL COMMENT 'Object type: MENU/PAGE',
  name VARCHAR(64) NOT NULL COMMENT 'Object Name',
  category_id BIGINT NULL COMMENT 'Category ID',
  path VARCHAR(128) NOT NULL COMMENT 'Object Path',
  location ENUM('TOP','SIDEBAR','PROFILE','PAGE') NOT NULL COMMENT 'Location',
  description VARCHAR(255) NULL COMMENT 'Object Description',
  sort INT NOT NULL DEFAULT 0 COMMENT 'Sort Order',
  status TINYINT NOT NULL DEFAULT 1 COMMENT 'Status: 1 enabled, 0 disabled',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  UNIQUE KEY uq_feature_object_path (path),
  KEY idx_feature_object_category (category_id, sort),
  KEY idx_feature_object_parent (parent_id),
  KEY idx_feature_object_type (type, sort),
  CONSTRAINT fk_feature_object_category FOREIGN KEY (category_id) REFERENCES feature_object_categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Feature object';

-- =========================
-- Roles and authorization (within tenant)
-- =========================
CREATE TABLE roles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Role ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  type ENUM('ADMIN','USER') NOT NULL DEFAULT 'USER' COMMENT 'Role Type',
  name VARCHAR(64) NOT NULL COMMENT 'Role Name',
  description VARCHAR(255) NULL COMMENT 'Role Description',
  level INT NOT NULL DEFAULT 100 COMMENT 'Role level (smaller value means higher privilege)',
  status TINYINT NOT NULL DEFAULT 1 COMMENT 'Status: 1 enabled, 0 disabled',
  sort INT NOT NULL DEFAULT 0 COMMENT 'Sort Order',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  UNIQUE KEY uq_role_name (tenant_id, name),
  KEY idx_role_tenant (tenant_id),
  KEY idx_role_level (tenant_id, level, sort, id),
  CONSTRAINT fk_role_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Role';

CREATE TABLE user_roles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  user_id BIGINT NOT NULL COMMENT 'User ID',
  role_id BIGINT NOT NULL COMMENT 'Role ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  UNIQUE KEY uq_user_role (tenant_id, user_id, role_id),
  KEY idx_user_role_user (tenant_id, user_id),
  KEY idx_user_role_role (tenant_id, role_id),
  CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES roles(id),
  CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='User-role relation';

CREATE TABLE role_permissions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  role_id BIGINT NOT NULL COMMENT 'Role ID',
  object_id BIGINT NOT NULL COMMENT 'Feature object ID',
  permission_id BIGINT NOT NULL COMMENT 'Permission ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  UNIQUE KEY uq_role_permission (tenant_id, role_id, object_id, permission_id),
  KEY idx_role_permission_role (tenant_id, role_id),
  KEY idx_role_permission_object (tenant_id, object_id),
  CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES roles(id),
  CONSTRAINT fk_role_permission_object FOREIGN KEY (object_id) REFERENCES feature_objects(id),
  CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES permissions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Role-permission relation';

CREATE TABLE tenant_feature_permissions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Grant ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  object_id BIGINT NOT NULL COMMENT 'Feature object ID',
  permission_id BIGINT NOT NULL COMMENT 'Highest permission available to tenant',
  status TINYINT NOT NULL DEFAULT 1 COMMENT 'Status: 1 enabled, 0 disabled',
  grant_source ENUM('SYSTEM','ADMIN') NOT NULL DEFAULT 'ADMIN' COMMENT 'Grant Source',
  granted_by BIGINT NULL COMMENT 'Granted by User ID',
  granted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Granted At',
  updated_by BIGINT NULL COMMENT 'Updated by User ID',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  UNIQUE KEY uq_tenant_feature (tenant_id, object_id),
  KEY idx_tenant_feature_status (tenant_id, status),
  CONSTRAINT fk_tenant_feature_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_tenant_feature_object FOREIGN KEY (object_id) REFERENCES feature_objects(id),
  CONSTRAINT fk_tenant_feature_permission FOREIGN KEY (permission_id) REFERENCES permissions(id),
  CONSTRAINT fk_tenant_feature_granted_by FOREIGN KEY (granted_by) REFERENCES users(id),
  CONSTRAINT fk_tenant_feature_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Tenant feature authorization';

CREATE TABLE tenant_feature_audit (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Audit ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  object_id BIGINT NOT NULL COMMENT 'Feature object ID',
  action ENUM('GRANT','REVOKE','ENABLE','DISABLE','UPDATE_PERMISSION') NOT NULL COMMENT 'Action',
  before_status TINYINT NULL COMMENT 'Status before change',
  after_status TINYINT NOT NULL COMMENT 'Status after change',
  before_permission_id BIGINT NULL COMMENT 'Permission before change',
  after_permission_id BIGINT NULL COMMENT 'Permission after change',
  operator_user_id BIGINT NOT NULL COMMENT 'Operator User ID',
  operator_tenant_id BIGINT NOT NULL COMMENT 'Operator tenant ID (super admin = 0)',
  reason VARCHAR(255) NULL COMMENT 'Reason',
  request_id VARCHAR(64) NULL COMMENT 'Request ID / Trace ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Operation Time',
  KEY idx_tenant_feature_audit_time (tenant_id, created_at),
  KEY idx_tenant_feature_audit_object (tenant_id, object_id),
  KEY idx_tenant_feature_audit_operator (operator_tenant_id, operator_user_id),
  CONSTRAINT fk_tenant_feature_audit_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_tenant_feature_audit_object FOREIGN KEY (object_id) REFERENCES feature_objects(id),
  CONSTRAINT fk_tenant_feature_audit_before_permission FOREIGN KEY (before_permission_id) REFERENCES permissions(id),
  CONSTRAINT fk_tenant_feature_audit_after_permission FOREIGN KEY (after_permission_id) REFERENCES permissions(id),
  CONSTRAINT fk_tenant_feature_audit_operator FOREIGN KEY (operator_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Tenant feature authorization audit';

-- =========================
-- Invitation
-- =========================
CREATE TABLE user_invitations (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Invitation ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  inviter_user_id BIGINT NOT NULL COMMENT 'Inviter User ID',
  invite_code VARCHAR(64) NOT NULL COMMENT 'Invitation code',
  status TINYINT NOT NULL DEFAULT 0 COMMENT 'Status: 0 pending, 1 accepted, 2 expired, 3 canceled, 4 processing, 5 failed',
  expires_at DATETIME NULL COMMENT 'Expiration time',
  accepted_user_id BIGINT NULL COMMENT 'Accepted User ID',
  accepted_at DATETIME NULL COMMENT 'Accepted At',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  UNIQUE KEY uq_invite_code (invite_code),
  KEY idx_invite_tenant (tenant_id, status),
  CONSTRAINT fk_invite_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_invite_inviter FOREIGN KEY (inviter_user_id) REFERENCES users(id),
  CONSTRAINT fk_invite_accepted_user FOREIGN KEY (accepted_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='UserInvitation';

CREATE TABLE user_invitation_roles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key ID',
  invitation_id BIGINT NOT NULL COMMENT 'Invitation ID',
  role_id BIGINT NOT NULL COMMENT 'Role ID',
  UNIQUE KEY uq_invitation_role (invitation_id, role_id),
  CONSTRAINT fk_invitation_role_invitation FOREIGN KEY (invitation_id) REFERENCES user_invitations(id),
  CONSTRAINT fk_invitation_role_role FOREIGN KEY (role_id) REFERENCES roles(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Invitation-role relation';

-- =========================
-- AI related
-- =========================
CREATE TABLE ai_provider (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Provider ID',
  code VARCHAR(32) NOT NULL COMMENT 'Provider code (openai/anthropic/...)',
  name VARCHAR(64) NOT NULL COMMENT 'Provider Name',
  base_url VARCHAR(255) NULL COMMENT 'Default base URL (frontend prefill only)',
  model_ids JSON NULL COMMENT 'Supported model list (frontend dropdown)',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  UNIQUE KEY uq_ai_provider_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI provider';

CREATE TABLE ai_model (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Model ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  provider_model_id VARCHAR(128) NOT NULL COMMENT 'Model ID (unique within provider)',
  name VARCHAR(128) NOT NULL COMMENT 'Display name',
  provider_id BIGINT NOT NULL COMMENT 'Provider ID',
  model_type ENUM('chat','embeddings','reranking','code') NOT NULL COMMENT 'Model Type',
  description VARCHAR(512) NULL COMMENT 'Description',
  tags JSON NULL COMMENT 'Tags',
  context_tokens INT NULL COMMENT 'Context length (tokens)',
  input_price_usd DECIMAL(18,6) NULL COMMENT 'Input price (USD / million tokens)',
  output_price_usd DECIMAL(18,6) NULL COMMENT 'Output price (USD / million tokens)',
  embedding_dimension INT NULL COMMENT 'Embedding dimension (embeddings only)',
  api_key TEXT NULL COMMENT 'Encrypted API key (ENCv1)',
  base_url VARCHAR(255) NULL COMMENT 'Base URL',
  status ENUM('CONNECT','ACTIVE') NOT NULL DEFAULT 'CONNECT' COMMENT 'Connection status: CONNECT=not connected, ACTIVE=connected',
  created_by BIGINT NOT NULL COMMENT 'Created by user ID (audit)',
  updated_by BIGINT NULL COMMENT 'Updated by user ID (audit)',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  UNIQUE KEY uq_ai_model_tenant_provider_model (tenant_id, provider_id, provider_model_id),
  KEY idx_ai_model_tenant_provider_type (tenant_id, provider_id, model_type),
  KEY idx_ai_model_tenant_id (tenant_id, id),
  CONSTRAINT fk_ai_model_provider FOREIGN KEY (provider_id) REFERENCES ai_provider(id),
  CONSTRAINT fk_ai_model_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI model (tenant model pool)';

CREATE TABLE ai_model_grant (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Grant ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  user_id BIGINT NOT NULL COMMENT 'User ID',
  model_id BIGINT NOT NULL COMMENT 'Model ID (references ai_model.id)',
  permission_id BIGINT NOT NULL COMMENT 'Permission ID (references permissions.id)',
  is_default TINYINT NOT NULL DEFAULT 0 COMMENT 'Is default model: 1 yes, 0 no',
  granted_by BIGINT NULL COMMENT 'Granted by User ID',
  granted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Granted At',
  updated_by BIGINT NULL COMMENT 'Updated by User ID',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  expires_at DATETIME NULL DEFAULT NULL COMMENT 'Expiration time, NULL means never expires',
  default_slot TINYINT GENERATED ALWAYS AS (
    CASE WHEN is_default = 1 THEN 1 ELSE NULL END
  ) STORED COMMENT 'Default-constraint helper column',
  UNIQUE KEY uq_ai_model_grant_tenant_user_model (tenant_id, user_id, model_id),
  UNIQUE KEY uq_ai_model_grant_tenant_user_default (tenant_id, user_id, default_slot),
  KEY idx_ai_model_grant_tenant_user_permission (tenant_id, user_id, permission_id),
  KEY idx_ai_model_grant_tenant_model_permission (tenant_id, model_id, permission_id),
  KEY idx_ai_model_grant_tenant_expires (tenant_id, expires_at),
  CONSTRAINT fk_ai_model_grant_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_ai_model_grant_tenant_user FOREIGN KEY (tenant_id, user_id) REFERENCES tenant_users(tenant_id, user_id),
  CONSTRAINT fk_ai_model_grant_tenant_model FOREIGN KEY (tenant_id, model_id) REFERENCES ai_model(tenant_id, id),
  CONSTRAINT fk_ai_model_grant_permission FOREIGN KEY (permission_id) REFERENCES permissions(id),
  CONSTRAINT fk_ai_model_grant_granted_by FOREIGN KEY (tenant_id, granted_by) REFERENCES tenant_users(tenant_id, user_id),
  CONSTRAINT fk_ai_model_grant_updated_by FOREIGN KEY (tenant_id, updated_by) REFERENCES tenant_users(tenant_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI model authorization relation';

CREATE TABLE ai_usage (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  user_id BIGINT NOT NULL COMMENT 'User ID',
  model_id BIGINT NOT NULL COMMENT 'Model ID (references ai_model.id)',
  call_count BIGINT NOT NULL DEFAULT 0 COMMENT 'Call count',
  prompt_tokens BIGINT NOT NULL DEFAULT 0 COMMENT 'Accumulated input tokens',
  completion_tokens BIGINT NOT NULL DEFAULT 0 COMMENT 'Accumulated output tokens',
  total_tokens BIGINT NOT NULL DEFAULT 0 COMMENT 'Accumulated total tokens',
  total_cost_usd DECIMAL(18,8) NOT NULL DEFAULT 0 COMMENT 'Accumulated cost (USD)',
  last_used_at DATETIME NULL COMMENT 'Last used at',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  UNIQUE KEY uq_ai_usage_tenant_user_model (tenant_id, user_id, model_id),
  KEY idx_ai_usage_tenant_user_last_used (tenant_id, user_id, last_used_at),
  KEY idx_ai_usage_tenant_model_last_used (tenant_id, model_id, last_used_at),
  CONSTRAINT fk_ai_usage_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_ai_usage_tenant_user FOREIGN KEY (tenant_id, user_id) REFERENCES tenant_users(tenant_id, user_id),
  CONSTRAINT fk_ai_usage_tenant_model FOREIGN KEY (tenant_id, model_id) REFERENCES ai_model(tenant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI model usage statistics';

-- =========================
-- Studio business data
-- =========================
CREATE TABLE projects (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Project ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  name VARCHAR(128) NOT NULL COMMENT 'Project Name',
  description VARCHAR(512) NULL COMMENT 'Project Description',
  owner_id BIGINT NOT NULL COMMENT 'Project Owner ID',
  status TINYINT NOT NULL COMMENT 'Project Status',
  tags JSON NULL COMMENT 'Project Tags',
  is_favorite TINYINT NOT NULL DEFAULT 0 COMMENT 'Is favorite',
  is_visible TINYINT NOT NULL DEFAULT 1 COMMENT 'Is visible',
  member_count INT NOT NULL DEFAULT 1 COMMENT 'Member count',
  last_accessed_at DATETIME NULL COMMENT 'Last accessed at',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete',
  KEY idx_project_tenant (tenant_id),
  KEY idx_project_owner (tenant_id, owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Projects';

CREATE TABLE job_workflow (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Workflow ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  project_id BIGINT NOT NULL COMMENT 'Project ID',
  workflow_name VARCHAR(128) NOT NULL COMMENT 'Workflow Name',
  trigger_type TINYINT NOT NULL COMMENT 'Trigger type',
  trigger_value VARCHAR(128) NULL COMMENT 'Trigger value',
  timeout_seconds INT NULL COMMENT 'Timeout seconds',
  max_retry_times INT NULL COMMENT 'Maximum retry count',
  priority INT NULL COMMENT 'Priority',
  status TINYINT NOT NULL DEFAULT 0 COMMENT 'Status',
  description VARCHAR(512) NULL COMMENT 'Description',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  KEY idx_workflow_tenant (tenant_id),
  KEY idx_workflow_project (tenant_id, project_id),
  CONSTRAINT fk_workflow_project FOREIGN KEY (project_id) REFERENCES projects(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Workflow';

CREATE TABLE job_component (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Component ID',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT 'Tenant ID (0 means system tenant)',
  component_code VARCHAR(64) NOT NULL COMMENT 'Component Code',
  component_name VARCHAR(128) NOT NULL COMMENT 'Component Name',
  component_type VARCHAR(64) NOT NULL COMMENT 'Component Type',
  job_params JSON NULL COMMENT 'Parameter definition',
  description VARCHAR(512) NULL COMMENT 'Description',
  icon VARCHAR(128) NULL COMMENT 'Icon',
  color VARCHAR(32) NULL COMMENT 'Color',
  status TINYINT NOT NULL DEFAULT 1 COMMENT 'Status: 1 enabled, 0 disabled',
  sort_order INT NOT NULL DEFAULT 0 COMMENT 'Sort Order',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  UNIQUE KEY uq_component_code (tenant_id, component_code),
  KEY idx_component_type (tenant_id, component_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Task component';

CREATE TABLE job_info (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Task ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  workflow_id BIGINT NOT NULL COMMENT 'Workflow ID',
  job_name VARCHAR(128) NOT NULL COMMENT 'Task Name',
  job_type BIGINT NOT NULL COMMENT 'Task type (component ID)',
  job_params JSON NULL COMMENT 'Task parameters',
  timeout_seconds INT NULL COMMENT 'Timeout seconds',
  max_retry_times INT NULL COMMENT 'Maximum retry count',
  retry_interval INT NULL COMMENT 'Retry interval (seconds)',
  priority INT NULL COMMENT 'Priority',
  position_x DOUBLE NULL COMMENT 'Canvas X coordinate',
  position_y DOUBLE NULL COMMENT 'Canvas Y coordinate',
  description VARCHAR(512) NULL COMMENT 'Description',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  KEY idx_job_tenant (tenant_id),
  KEY idx_job_workflow (tenant_id, workflow_id),
  CONSTRAINT fk_job_workflow FOREIGN KEY (workflow_id) REFERENCES job_workflow(id),
  CONSTRAINT fk_job_component FOREIGN KEY (job_type) REFERENCES job_component(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Task';

CREATE TABLE job_dependency (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Dependency ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  workflow_id BIGINT NOT NULL COMMENT 'Workflow ID',
  job_id BIGINT NOT NULL COMMENT 'Task ID',
  parent_job_id BIGINT NOT NULL COMMENT 'Parent Task ID',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  KEY idx_dependency_tenant (tenant_id),
  KEY idx_dependency_workflow (tenant_id, workflow_id),
  KEY idx_dependency_job (tenant_id, job_id),
  CONSTRAINT fk_dependency_workflow FOREIGN KEY (workflow_id) REFERENCES job_workflow(id),
  CONSTRAINT fk_dependency_job FOREIGN KEY (job_id) REFERENCES job_info(id),
  CONSTRAINT fk_dependency_parent_job FOREIGN KEY (parent_job_id) REFERENCES job_info(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Task dependencies';

CREATE TABLE knowledge_namespace (
  namespace_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Namespace ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  namespace VARCHAR(128) NOT NULL COMMENT 'Namespace identifier',
  description VARCHAR(512) NULL COMMENT 'Namespace description',
  created_by BIGINT NOT NULL COMMENT 'Created by User ID',
  status TINYINT NOT NULL DEFAULT 1 COMMENT 'Status: 1 enabled, 0 disabled',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  PRIMARY KEY (namespace_id),
  UNIQUE KEY uk_namespace_creator (tenant_id, created_by, namespace),
  KEY idx_namespace_tenant (tenant_id),
  KEY idx_namespace_creator (tenant_id, created_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Knowledge namespace';

CREATE TABLE knowledge_document (
  document_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Document ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  namespace_id BIGINT UNSIGNED NOT NULL COMMENT 'Namespace ID',
  doc_uid VARCHAR(64) NOT NULL COMMENT 'Stable document ID',
  title VARCHAR(255) NOT NULL COMMENT 'Document title',
  file_type VARCHAR(32) NOT NULL COMMENT 'File type',
  size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'File size (bytes)',
  storage_uri VARCHAR(1024) NULL COMMENT 'Storage URI',
  storage_type VARCHAR(32) NULL COMMENT 'Storage type',
  storage_key VARCHAR(255) NULL COMMENT 'Object storage key',
  status VARCHAR(32) NOT NULL DEFAULT 'processing' COMMENT 'Processing status',
  chunk_count INT NOT NULL DEFAULT 0 COMMENT 'Chunk count',
  token_count INT NOT NULL DEFAULT 0 COMMENT 'Token statistics',
  error_message VARCHAR(1024) NULL COMMENT 'Failure reason',
  embedding_model_id BIGINT UNSIGNED NULL COMMENT 'Embedding model ID',
  embedding_dimension INT NULL COMMENT 'Vector dimension',
  chunk_mode VARCHAR(32) NULL COMMENT 'Chunking mode',
  chunk_config_json JSON NULL COMMENT 'Chunking config snapshot',
  last_chunked_at TIMESTAMP NULL COMMENT 'Last chunked at',
  created_by BIGINT NOT NULL COMMENT 'Created by User ID',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Soft delete',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  PRIMARY KEY (document_id),
  KEY idx_doc_namespace (tenant_id, namespace_id),
  KEY idx_doc_namespace_status (tenant_id, namespace_id, status),
  KEY idx_doc_created_by (tenant_id, created_by),
  KEY idx_doc_uid (tenant_id, doc_uid),
  KEY idx_doc_embedding_model (tenant_id, embedding_model_id),
  CONSTRAINT fk_doc_namespace FOREIGN KEY (namespace_id) REFERENCES knowledge_namespace(namespace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Knowledge document';

CREATE TABLE knowledge_document_job (
  job_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Task ID',
  tenant_id BIGINT NOT NULL COMMENT 'Tenant ID',
  namespace_id BIGINT UNSIGNED NOT NULL COMMENT 'Namespace ID',
  document_id BIGINT UNSIGNED NOT NULL COMMENT 'Document ID',
  job_type VARCHAR(32) NOT NULL COMMENT 'Task Type',
  status VARCHAR(32) NOT NULL DEFAULT 'queued' COMMENT 'Task Status',
  progress TINYINT NOT NULL DEFAULT 0 COMMENT 'Progress percentage',
  progress_seq BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Progress sequence number',
  total_chunks INT NOT NULL DEFAULT 0 COMMENT 'Estimated chunk count',
  processed_chunks INT NOT NULL DEFAULT 0 COMMENT 'Processed chunk count',
  error_message VARCHAR(1024) NULL COMMENT 'Failure reason',
  started_at TIMESTAMP NULL COMMENT 'Start time',
  finished_at TIMESTAMP NULL COMMENT 'Completed at',
  created_by BIGINT NOT NULL COMMENT 'Created by User ID',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
  PRIMARY KEY (job_id),
  KEY idx_job_namespace (tenant_id, namespace_id),
  KEY idx_job_document (tenant_id, document_id),
  KEY idx_job_status (tenant_id, status),
  KEY idx_job_created_by (tenant_id, created_by),
  CONSTRAINT fk_kdj_namespace FOREIGN KEY (namespace_id) REFERENCES knowledge_namespace(namespace_id),
  CONSTRAINT fk_kdj_document FOREIGN KEY (document_id) REFERENCES knowledge_document(document_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Document chunking task';
