# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datapillar/security/v1/common.proto
# Protobuf Python Version: 4.25.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#datapillar/security/v1/common.proto\x12\x16\x64\x61tapillar.security.v1\"\xdd\x01\n\x07RpcMeta\x12\x18\n\x10protocol_version\x18\x01 \x01(\t\x12\x16\n\x0e\x63\x61ller_service\x18\x02 \x01(\t\x12\x10\n\x08trace_id\x18\x03 \x01(\t\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x12\x11\n\tclient_ip\x18\x05 \x01(\t\x12\x39\n\x05\x61ttrs\x18\x06 \x03(\x0b\x32*.datapillar.security.v1.RpcMeta.AttrsEntry\x1a,\n\nAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xc6\x01\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12;\n\x07\x63ontext\x18\x04 \x03(\x0b\x32*.datapillar.security.v1.Error.ContextEntry\x12\x10\n\x08trace_id\x18\x05 \x01(\t\x12\x11\n\tretryable\x18\x06 \x01(\x08\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd5\x01\n\tPrincipal\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x11\n\ttenant_id\x18\x02 \x01(\x03\x12\x10\n\x08username\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\r\n\x05roles\x18\x05 \x03(\t\x12\x15\n\rimpersonation\x18\x06 \x01(\x08\x12\x15\n\ractor_user_id\x18\x07 \x01(\x03\x12\x17\n\x0f\x61\x63tor_tenant_id\x18\x08 \x01(\x03\x12\x0b\n\x03sid\x18\t \x01(\t\x12\x0b\n\x03jti\x18\n \x01(\t\x12\x13\n\x0btenant_code\x18\x0b \x01(\t*\xca\x01\n\x08\x44\x65nyCode\x12\x19\n\x15\x44\x45NY_CODE_UNSPECIFIED\x10\x00\x12\x11\n\rTOKEN_MISSING\x10\x01\x12\x11\n\rTOKEN_INVALID\x10\x02\x12\x11\n\rTOKEN_EXPIRED\x10\x03\x12\x13\n\x0fSESSION_REVOKED\x10\x04\x12\x13\n\x0fTENANT_DISABLED\x10\x05\x12\x11\n\rUSER_DISABLED\x10\x06\x12\x15\n\x11PERMISSION_DENIED\x10\x07\x12\x16\n\x12SYSTEM_UNAVAILABLE\x10\x08\x42/\n+com.sunny.datapillar.common.rpc.security.v1P\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datapillar.security.v1.common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals['DESCRIPTOR']._options = None
    _globals['DESCRIPTOR']._serialized_options = (
        b'\n+com.sunny.datapillar.common.rpc.security.v1P\001'
    )
    _globals['_RPCMETA_ATTRSENTRY']._options = None
    _globals['_RPCMETA_ATTRSENTRY']._serialized_options = b'8\001'
    _globals['_ERROR_CONTEXTENTRY']._options = None
    _globals['_ERROR_CONTEXTENTRY']._serialized_options = b'8\001'
    _globals['_DENYCODE']._serialized_start = 705
    _globals['_DENYCODE']._serialized_end = 907
    _globals['_RPCMETA']._serialized_start = 64
    _globals['_RPCMETA']._serialized_end = 285
    _globals['_RPCMETA_ATTRSENTRY']._serialized_start = 241
    _globals['_RPCMETA_ATTRSENTRY']._serialized_end = 285
    _globals['_ERROR']._serialized_start = 288
    _globals['_ERROR']._serialized_end = 486
    _globals['_ERROR_CONTEXTENTRY']._serialized_start = 440
    _globals['_ERROR_CONTEXTENTRY']._serialized_end = 486
    _globals['_PRINCIPAL']._serialized_start = 489
    _globals['_PRINCIPAL']._serialized_end = 702
# @@protoc_insertion_point(module_scope)
