"""
ReAct schema - data models for plan/execute/reflect.

Core models:
- PlanTask: task in the plan
- Plan: plan (tasks + status)
- Reflection: reflection result
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from datapillar_oneagentic.utils.prompt_format import format_markdown
from datapillar_oneagentic.utils.time import now_ms
from datapillar_oneagentic.core.status import ExecutionStatus, ProcessStage
# ==================== Status enums ====================

TaskStatus = ExecutionStatus
PlanStatus = ExecutionStatus
NextAction = Literal["continue", "retry", "replan", "complete", "fail"]


# ==================== PlanTask ====================


class PlanTask(BaseModel):
    """
    Task in the plan.

    Generated by Planner and assigned to an agent.
    """

    id: str = Field(..., description="Task ID (t1, t2, ...)")
    description: str = Field(..., description="Task description")
    assigned_agent: str = Field(..., description="Assigned agent")
    status: TaskStatus = Field(default=ExecutionStatus.PENDING, description="Task status")
    depends_on: list[str] = Field(default_factory=list, description="Dependent task IDs")
    result: str | None = Field(default=None, description="Execution result")
    error: str | None = Field(default=None, description="Error message (if failed)")

    def is_ready(self, completed_tasks: set[str]) -> bool:
        """Return True if dependencies are completed."""
        return all(dep in completed_tasks for dep in self.depends_on)

    def mark_running(self) -> None:
        """Mark as running."""
        self.status = ExecutionStatus.RUNNING

    def mark_completed(self, result: str) -> None:
        """Mark as completed."""
        self.status = ExecutionStatus.COMPLETED
        self.result = result

    def mark_failed(self, error: str) -> None:
        """Mark as failed."""
        self.status = ExecutionStatus.FAILED
        self.error = error


# ==================== Plan ====================


class Plan(BaseModel):
    """
    Plan.

    Generated by Planner; includes goal and tasks.
    Executor runs tasks and Reflector evaluates results.
    """

    goal: str = Field(..., description="User goal")
    tasks: list[PlanTask] = Field(default_factory=list, description="Task list")
    status: PlanStatus = Field(default=ExecutionStatus.PENDING, description="Plan status")
    stage: ProcessStage = Field(default=ProcessStage.PLANNING, description="Plan stage")
    current_task_id: str | None = Field(default=None, description="Current task ID")
    retry_count: int = Field(default=0, description="Retry count")
    max_retries: int = Field(default=3, description="Maximum retries")
    created_at_ms: int = Field(default_factory=now_ms, description="Created time")
    updated_at_ms: int = Field(default_factory=now_ms, description="Updated time")

    def add_task(
        self,
        description: str,
        assigned_agent: str,
        depends_on: list[str] | None = None,
    ) -> PlanTask:
        """Add a task."""
        task_id = f"t{len(self.tasks) + 1}"
        task = PlanTask(
            id=task_id,
            description=description,
            assigned_agent=assigned_agent,
            depends_on=depends_on or [],
        )
        self.tasks.append(task)
        self.updated_at_ms = now_ms()
        return task

    def get_task(self, task_id: str) -> PlanTask | None:
        """Get a task by ID."""
        for task in self.tasks:
            if task.id == task_id:
                return task
        return None

    def get_completed_ids(self) -> set[str]:
        """Return completed task IDs."""
        return {t.id for t in self.tasks if t.status == ExecutionStatus.COMPLETED}

    def get_next_task(self) -> PlanTask | None:
        """Return the next ready task."""
        completed = self.get_completed_ids()
        for task in self.tasks:
            if task.status == ExecutionStatus.PENDING and task.is_ready(completed):
                return task
        return None

    def get_current_task(self) -> PlanTask | None:
        """Return the current task."""
        if not self.current_task_id:
            return None
        return self.get_task(self.current_task_id)

    def is_all_completed(self) -> bool:
        """Return True if all tasks are completed."""
        return all(
            t.status in (ExecutionStatus.COMPLETED, ExecutionStatus.SKIPPED)
            for t in self.tasks
        )

    def has_failed_task(self) -> bool:
        """Return True if any task failed."""
        return any(t.status == ExecutionStatus.FAILED for t in self.tasks)

    def can_retry(self) -> bool:
        """Return True if retry is allowed."""
        return self.retry_count < self.max_retries

    def increment_retry(self) -> None:
        """Increment retry count."""
        self.retry_count += 1
        self.updated_at_ms = now_ms()

    def to_prompt(self, *, include_title: bool = True) -> str:
        """Render as a prompt string."""
        task_lines: list[str] = []
        for task in self.tasks:
            status_marker = f"[{task.status.value}]"
            deps = f" (depends on: {', '.join(task.depends_on)})" if task.depends_on else ""
            line = f"- {status_marker} [{task.id}] {task.description} -> {task.assigned_agent}{deps}"
            if task.result:
                line += f" | Result: {task.result}"
            if task.error:
                line += f" | Error: {task.error}"
            task_lines.append(line)

        if not include_title:
            lines = [f"- Goal: {self.goal}"]
            lines.extend(task_lines)
            return "\n".join(lines).strip()

        tasks_text = "\n".join(task_lines).strip()
        return format_markdown(
            title="Plan",
            sections=[
                ("Goal", self.goal),
                ("Tasks", tasks_text),
            ],
        )


# ==================== Reflection ====================


class Reflection(BaseModel):
    """
    Reflection result.

    Generated by Reflector; evaluates results and decides next steps.
    """

    goal_achieved: bool = Field(..., description="Whether the goal is achieved")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence 0-1")
    summary: str = Field(..., description="Evaluation summary")
    issues: list[str] = Field(default_factory=list, description="Identified issues")
    suggestions: list[str] = Field(default_factory=list, description="Improvement suggestions")
    next_action: NextAction = Field(..., description="Next action")
    reason: str = Field(..., description="Decision rationale")

    def should_continue(self) -> bool:
        """Return True if should continue."""
        return self.next_action == "continue"

    def should_retry(self) -> bool:
        """Return True if should retry."""
        return self.next_action == "retry"

    def should_replan(self) -> bool:
        """Return True if should replan."""
        return self.next_action == "replan"

    def is_complete(self) -> bool:
        """Return True if complete."""
        return self.next_action == "complete"

    def is_failed(self) -> bool:
        """Return True if failed."""
        return self.next_action == "fail"


# ==================== LLM output schema ====================


class PlanTaskOutput(BaseModel):
    """Planner LLM output task."""

    description: str = Field(..., description="Task description")
    assigned_agent: str = Field(..., description="Assigned agent_id")
    depends_on: list[str] = Field(default_factory=list, description="Dependent task indices (1-based)")


class PlannerOutput(BaseModel):
    """Planner LLM output."""

    understanding: str = Field(..., description="Understanding of the user goal")
    tasks: list[PlanTaskOutput] = Field(..., description="Task list")


class ReflectorOutput(BaseModel):
    """Reflector LLM output."""

    goal_achieved: bool = Field(..., description="Whether the goal is achieved")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence 0-1")
    summary: str = Field(..., description="Evaluation summary")
    issues: list[str] = Field(default_factory=list, description="Identified issues")
    suggestions: list[str] = Field(default_factory=list, description="Improvement suggestions")
    next_action: NextAction = Field(..., description="Next action: continue/retry/replan/complete/fail")
    reason: str = Field(..., description="Decision rationale")
