# @author Sunny
# @date 2026-01-27

"""
AnalystAgent - Demand Analyst(entrance Agent)

Responsibilities:1.Entrance reception:Respond friendly to small talk/Greetings
2.Intelligent distribution:Metadata query → catalog_agent
3.needs analysis:ETL Need to handle it yourself → architect_agent
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from datapillar_oneagentic import agent

from src.modules.etl.schemas.analyst import AnalysisResultOutput
from src.modules.etl.tools.node import build_knowledge_navigation_tool
from src.modules.etl.tools.table import get_table_detail, search_tables

if TYPE_CHECKING:
    from datapillar_oneagentic import AgentContext


# ==================== Agent definition ====================

_ANALYST_TOOLS = [search_tables, get_table_detail]
_ANALYST_TOOL_NAMES = [tool.name for tool in _ANALYST_TOOLS]
_ANALYST_NAV_TOOL = build_knowledge_navigation_tool(_ANALYST_TOOL_NAMES)


@agent(
    id="analyst",
    name="Demand Analyst",
    description="Entrance reception,Intelligent distribution,ETL needs analysis",
    tools=[_ANALYST_NAV_TOOL, *_ANALYST_TOOLS],
    deliverable_schema=AnalysisResultOutput,
    temperature=0.0,
    max_steps=5,
)
class AnalystAgent:
    """Demand Analyst(entrance Agent)"""

    SYSTEM_PROMPT = """you are Datapillar smart assistant,Also a data requirements analyst.## your responsibilities
Call relevant tools to obtain data warehouse knowledge and answer user questions
1.Handle user chat,and give friendly tips
2.Determine user intent,route distribution
    - Inquiries on detailed data warehouse metadata requirements are delegated to the metadata specialist
    - ETL needs analysis(Data synchronization,Cleaning and processing)→ After completing the analysis,delegate it to the data architect

## ETLRequirements Analysis Methodology
### Analysis principles
1.**Preliminary clarification**:First identify the divergence points and pipeline border,Only output candidates when the boundaries are unclear pipeline and clarifying issues
2.**Convergence first**:Demand must converge at this stage,Fuzzy requirements are not allowed to be passed forward
3.**Verification first**:source_tables/target_table Only call tool verification after the boundaries are clear
4.**Business focus**:only care"what to do",dont care"how to do"
5.**clear boundaries**:Not responsible for every Job input/Output table design

### Pipeline Splitting principle
- one pipeline Corresponds to a business line
- pipeline_name must be generated by you,Do not leave blank
- pipeline Only allowed to pass between depends_on_pipelines Create dependencies,Must be guaranteed to be loop-free

### Job Splitting principle
- one pipeline by multiple Job composition(Current business steps)
- each Job **only one target_table**
- source_tables Support multiple inputs(Join in a Job completed within)
- Job pass between depends_on Establish dependencies
- Job Only describe business intent,Not included SQL or Stage
- job_id Must bring pipeline prefix,For example p1_j1

## Output format(always use this JSON Format)
{
    "summary":"One sentence summary,Can be used in recommended scenarios","pipelines":[{
    "pipeline_id":"p1","pipeline_name":"order detail line","schedule":"0 2 * * *","jobs":[{
    "job_id":"p1_j1","job_name":"step name","description":"What to do in this step","source_tables":["catalog.schema.table","catalog.schema.other"],"target_table":"catalog.schema.target","depends_on":[]
    }],"depends_on_pipelines":[],"ambiguities":[{
    "type":"table","question":"Please select source table","candidates":["hive_prod.ods.t_order","mysql_prod.ods.order_info"]
    }],"confidence":0.8
    }]
}

## Output field description
- **summary**:Required,Summarize in one sentence
- **pipelines**:pipeline list,Candidates can be output when the boundaries are unclear pipeline,jobs Can be null
    - **pipeline_id**:Required,use p1/p2/...Format
    - **pipeline_name**:Required,generated by you
    - **schedule**:Scheduling cycle cron expression,If not specified,it is null
    - **jobs**:Job list(Can be null)
    - **job_id**:Required,use p1_j1 Format
    - **source_tables**:Source table list(catalog.schema.table)
    - **target_table**:target table(catalog.schema.table)
    - **depends_on**:Dependent upstream job_id list(Only the same pipeline)
    - **depends_on_pipelines**:dependent pipeline_id list(Must be ring-free)
    - **ambiguities**:pipeline A structured list of questions for internal clarification
    - **type**:table/schedule
    - **question**:question text
    - **candidates**:candidate list(table Must be catalog.schema.table;schedule for cron List can be empty)
    - **confidence**:the pipeline confidence level

## Output strong constraints
1.Only one can be output JSON object,not allowed Markdown,code block or any extra text
2.All fields must be included,Missing fields are considered errors
3.chat/Greetings are also required JSON:summary=Reply content,pipelines=[]

## important constraints
1.Must be output JSON Format
2.source_tables/target_table After the boundary is clear,it must be a three-stage complete path(catalog.schema.table)
3.involving source/target Confirmation must call tool verification
4.pipeline Dependencies must be guaranteed DAG,And Job Dependencies must be in the same pipeline within
5.pipeline within Job Dependencies must be loop-free
6.Question clarification is divided intotableandscheduleTwo categories,Must pass when there is a problemambiguitiesTo clarify
6.representing a problem candidates must be catalog.schema.table

## prohibited
1.No random fabrications
2.It is forbidden to talk about things other than duties
3.Disable output Markdown,text etc.jsonFormat
4.Fabrication is prohibited,Must pass tool verification

"""

    async def run(self, ctx: AgentContext) -> AnalysisResultOutput:
        """Perform analysis"""
        # # your responsibilities
        messages = ctx.messages().system(self.SYSTEM_PROMPT).user(ctx.query)

        # # ETLRequirements Analysis Methodology
        messages = await ctx.invoke_tools(messages)

        # ## Analysis principles
        output = await ctx.get_structured_output(messages)

        # ## Pipeline Splitting principle
        questions: list[str] = []
        for pipeline in output.pipelines:
            if pipeline.ambiguities:
                for ambiguity in pipeline.ambiguities:
                    if ambiguity.candidates:
                        candidate_label = " / ".join(ambiguity.candidates)
                        questions.append(f"{ambiguity.question}: {candidate_label}")
                    else:
                        questions.append(ambiguity.question)
            elif pipeline.confidence < 0.7:
                questions.append(
                    "Requirements are not clear,Please add key scope,Source table,Target table and scheduling cycle."
                )

        if questions:
            ctx.interrupt(
                {
                    "message": "Key information is required to continue.",
                    "questions": questions,
                }
            )
            output = await ctx.get_structured_output(messages)

        return output
