#!/bin/bash
#
# Datapillar Environment variable configuration
#
# Place this file in conf/ under directory，The startup script will be loaded automatically
#

# Datapillar version
export DATAPILLAR_VERSION="1.0.0"

# JVM Memory configuration
# export DATAPILLAR_MEM="-Xms512m -Xmx1024m"

# Java Home（If not set，Use system default）
# export JAVA_HOME="/usr/lib/jvm/java-21"

# Log directory（Default: ${DATAPILLAR_HOME}/logs）
# export DATAPILLAR_LOG_DIR="${DATAPILLAR_HOME}/logs"

# Configuration directory（Default: ${DATAPILLAR_HOME}/conf）
# export DATAPILLAR_CONF_DIR="${DATAPILLAR_HOME}/conf"

# Database configuration
export DB_HOST="${DB_HOST:-localhost}"
export DB_PORT="${DB_PORT:-3306}"
export DB_USERNAME="${DB_USERNAME:-root}"
export DB_PASSWORD="${DB_PASSWORD:-Sunny.123456}"

# Redis Configuration
export REDIS_HOST="${REDIS_HOST:-localhost}"
export REDIS_PORT="${REDIS_PORT:-6379}"
export REDIS_PASSWORD="${REDIS_PASSWORD:-}"
export REDIS_DATABASE="${REDIS_DATABASE:-0}"

# Airflow Configuration
export AIRFLOW_BASE_URL="${AIRFLOW_BASE_URL:-http://localhost:8080}"
export AIRFLOW_USERNAME="${AIRFLOW_USERNAME:-datapillar}"
export AIRFLOW_PASSWORD="${AIRFLOW_PASSWORD:-123456asd}"

# Gravitino Configuration（used for Flink SQL execute）
export GRAVITINO_URI="${GRAVITINO_URI:-http://localhost:8090}"
export GRAVITINO_METALAKE="${GRAVITINO_METALAKE:-oneMeta}"

# RocketMQ Configuration
export ROCKETMQ_NAME_SERVER="${ROCKETMQ_NAME_SERVER:-localhost:9876}"
export ROCKETMQ_BROKER_ADDR="${ROCKETMQ_BROKER_ADDR:-localhost:10911}"
export ROCKETMQ_CLUSTER_NAME="${ROCKETMQ_CLUSTER_NAME:-DefaultCluster}"
export ROCKETMQ_PRODUCER_GROUP="${ROCKETMQ_PRODUCER_GROUP:-ol-producer}"
export ROCKETMQ_ACCESS_KEY="${ROCKETMQ_ACCESS_KEY:-}"
export ROCKETMQ_SECRET_KEY="${ROCKETMQ_SECRET_KEY:-}"

# OpenLineage MQ Topics / Groups
export OPENLINEAGE_TOPIC_EVENTS="${OPENLINEAGE_TOPIC_EVENTS:-dp.openlineage.events.v1}"
export OPENLINEAGE_TOPIC_EMBEDDING="${OPENLINEAGE_TOPIC_EMBEDDING:-dp.openlineage.embedding.v1}"
export OPENLINEAGE_TOPIC_EVENTS_DLQ="${OPENLINEAGE_TOPIC_EVENTS_DLQ:-dp.openlineage.events.dlq.v1}"
export OPENLINEAGE_TOPIC_EMBEDDING_DLQ="${OPENLINEAGE_TOPIC_EMBEDDING_DLQ:-dp.openlineage.embedding.dlq.v1}"
export OPENLINEAGE_MQ_BOOTSTRAP_ENABLED="${OPENLINEAGE_MQ_BOOTSTRAP_ENABLED:-true}"
export OPENLINEAGE_TOPIC_READ_QUEUE_NUMS="${OPENLINEAGE_TOPIC_READ_QUEUE_NUMS:-8}"
export OPENLINEAGE_TOPIC_WRITE_QUEUE_NUMS="${OPENLINEAGE_TOPIC_WRITE_QUEUE_NUMS:-8}"
export OPENLINEAGE_GROUP_GRAPH="${OPENLINEAGE_GROUP_GRAPH:-ol-graph-consumer}"
export OPENLINEAGE_GROUP_EMBEDDING="${OPENLINEAGE_GROUP_EMBEDDING:-ol-embedding-consumer}"
export OPENLINEAGE_NEO4J_MIGRATIONS_ENABLED="${OPENLINEAGE_NEO4J_MIGRATIONS_ENABLED:-true}"
export OPENLINEAGE_NEO4J_VALIDATE_ON_MIGRATE="${OPENLINEAGE_NEO4J_VALIDATE_ON_MIGRATE:-true}"
export OPENLINEAGE_NEO4J_MIGRATIONS_LOCATIONS="${OPENLINEAGE_NEO4J_MIGRATIONS_LOCATIONS:-classpath:db/neo4j}"
export OPENLINEAGE_NEO4J_MIGRATIONS_INSTALLED_BY="${OPENLINEAGE_NEO4J_MIGRATIONS_INSTALLED_BY:-datapillar-openlineage}"
export OPENLINEAGE_KEY_STORAGE_TYPE="${OPENLINEAGE_KEY_STORAGE_TYPE:-local}"
export OPENLINEAGE_KEY_STORAGE_LOCAL_PATH="${OPENLINEAGE_KEY_STORAGE_LOCAL_PATH:-./data/datapillar/privkeys}"
# Object storage key backend (enable when OPENLINEAGE_KEY_STORAGE_TYPE=object)
export OPENLINEAGE_KEY_STORAGE_OBJECT_ENDPOINT="${OPENLINEAGE_KEY_STORAGE_OBJECT_ENDPOINT:-}"
export OPENLINEAGE_KEY_STORAGE_OBJECT_BUCKET="${OPENLINEAGE_KEY_STORAGE_OBJECT_BUCKET:-}"
export OPENLINEAGE_KEY_STORAGE_OBJECT_ACCESS_KEY="${OPENLINEAGE_KEY_STORAGE_OBJECT_ACCESS_KEY:-}"
export OPENLINEAGE_KEY_STORAGE_OBJECT_SECRET_KEY="${OPENLINEAGE_KEY_STORAGE_OBJECT_SECRET_KEY:-}"
export OPENLINEAGE_KEY_STORAGE_OBJECT_REGION="${OPENLINEAGE_KEY_STORAGE_OBJECT_REGION:-}"
export OPENLINEAGE_KEY_STORAGE_OBJECT_PREFIX="${OPENLINEAGE_KEY_STORAGE_OBJECT_PREFIX:-privkeys}"

# RocketMQ ACL account（used by services and bin/openlineage-mq-bootstrap.sh）
# export ROCKETMQ_ACCESS_KEY="global-ak"
# export ROCKETMQ_SECRET_KEY="global-sk"

# debug mode（Optional）
# export DATAPILLAR_DEBUG_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
