# -*- coding: utf-8 -*-
# @author Sunny
# @date 2026-01-27
"""Knowledge module."""

from datapillar_oneagentic.knowledge.config import (
    KnowledgeChunkConfig,
    KnowledgeChunkGeneralConfig,
    KnowledgeChunkParentChildConfig,
    KnowledgeChunkQAConfig,
    KnowledgeConfig,
    KnowledgeWindowConfig,
    MetadataFilterConfig,
    QueryExpansionConfig,
    QueryRouterConfig,
    ContextResolveConfig,
    KnowledgeRetrieveConfig,
    RerankConfig,
    RetrieveQualityConfig,
    RetrieveTuningConfig,
)
from datapillar_oneagentic.knowledge.models import (
    Attachment,
    Knowledge,
    KnowledgeChunk,
    KnowledgeDocument,
    KnowledgeSearchHit,
    KnowledgeRef,
    KnowledgeRetrieve,
    KnowledgeRetrieveResult,
    KnowledgeSource,
    ParsedDocument,
    SparseEmbeddingProvider,
    SourceSpan,
    merge_knowledge,
)
from datapillar_oneagentic.knowledge.service import (
    KnowledgeChunkEdit,
    KnowledgeChunkRequest,
    KnowledgeService,
)
from datapillar_oneagentic.knowledge.ingest.pipeline import KnowledgeIngestor
from datapillar_oneagentic.knowledge.chunker import KnowledgeChunker
from datapillar_oneagentic.knowledge.sparse_embedder import BM25SparseEmbedder
from datapillar_oneagentic.knowledge.evaluation import (
    ChunkingDocReport,
    ChunkingReport,
    ChunkingSummaryReport,
    EvalDocument,
    EvalQuery,
    EvalSet,
    EvaluationReport,
    KnowledgeEvaluator,
    LengthStats,
    RetrievalQueryReport,
    RetrievalReport,
    RetrievalSummaryReport,
    load_eval_set,
)

__all__ = [
    "Knowledge",
    "KnowledgeSource",
    "KnowledgeRetrieve",
    "ParsedDocument",
    "Attachment",
    "SourceSpan",
    "KnowledgeDocument",
    "KnowledgeChunk",
    "KnowledgeSearchHit",
    "KnowledgeRef",
    "KnowledgeRetrieveResult",
    "merge_knowledge",
    "SparseEmbeddingProvider",
    "KnowledgeChunkConfig",
    "KnowledgeChunkGeneralConfig",
    "KnowledgeChunkParentChildConfig",
    "KnowledgeChunkQAConfig",
    "KnowledgeWindowConfig",
    "KnowledgeRetrieveConfig",
    "MetadataFilterConfig",
    "QueryExpansionConfig",
    "QueryRouterConfig",
    "ContextResolveConfig",
    "RerankConfig",
    "RetrieveTuningConfig",
    "RetrieveQualityConfig",
    "KnowledgeConfig",
    "KnowledgeService",
    "KnowledgeChunkRequest",
    "KnowledgeChunkEdit",
    "KnowledgeIngestor",
    "KnowledgeChunker",
    "BM25SparseEmbedder",
    "EvalDocument",
    "EvalQuery",
    "EvalSet",
    "LengthStats",
    "ChunkingDocReport",
    "ChunkingSummaryReport",
    "ChunkingReport",
    "RetrievalQueryReport",
    "RetrievalSummaryReport",
    "RetrievalReport",
    "EvaluationReport",
    "KnowledgeEvaluator",
    "load_eval_set",
]
