--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file--
--  distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"). You may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--  http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.
--

-- Lineage Jobs table
CREATE TABLE IF NOT EXISTS lineage_jobs (
    job_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    namespace VARCHAR(256) NOT NULL,
    job_name VARCHAR(256) NOT NULL,
    job_type VARCHAR(64) DEFAULT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (job_id),
    UNIQUE (namespace, job_name)
);

COMMENT ON TABLE lineage_jobs IS 'lineage jobs';
COMMENT ON COLUMN lineage_jobs.job_id IS 'job id';
COMMENT ON COLUMN lineage_jobs.namespace IS 'job namespace';
COMMENT ON COLUMN lineage_jobs.job_name IS 'job name';
COMMENT ON COLUMN lineage_jobs.job_type IS 'job type';
COMMENT ON COLUMN lineage_jobs.created_at IS 'created timestamp';
COMMENT ON COLUMN lineage_jobs.updated_at IS 'updated timestamp';

-- Lineage Datasets table
CREATE TABLE IF NOT EXISTS lineage_datasets (
    dataset_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    namespace VARCHAR(256) NOT NULL,
    dataset_name VARCHAR(512) NOT NULL,
    dataset_type VARCHAR(64) DEFAULT NULL,
    schema_json TEXT DEFAULT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (dataset_id),
    UNIQUE (namespace, dataset_name)
);

COMMENT ON TABLE lineage_datasets IS 'lineage datasets';
COMMENT ON COLUMN lineage_datasets.dataset_id IS 'dataset id';
COMMENT ON COLUMN lineage_datasets.namespace IS 'dataset namespace';
COMMENT ON COLUMN lineage_datasets.dataset_name IS 'dataset name';
COMMENT ON COLUMN lineage_datasets.dataset_type IS 'dataset type';
COMMENT ON COLUMN lineage_datasets.schema_json IS 'dataset schema in JSON format';
COMMENT ON COLUMN lineage_datasets.created_at IS 'created timestamp';
COMMENT ON COLUMN lineage_datasets.updated_at IS 'updated timestamp';

-- Lineage Edges table (Job<->Dataset relationships)
CREATE TABLE IF NOT EXISTS lineage_edges (
    edge_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    source_type VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_id BIGINT NOT NULL,
    edge_type VARCHAR(32) NOT NULL,
    run_id VARCHAR(128) DEFAULT NULL,
    created_at BIGINT NOT NULL,
    PRIMARY KEY (edge_id)
);

CREATE INDEX IF NOT EXISTS lineage_edges_idx_source ON lineage_edges (source_type, source_id);
CREATE INDEX IF NOT EXISTS lineage_edges_idx_target ON lineage_edges (target_type, target_id);
CREATE INDEX IF NOT EXISTS lineage_edges_idx_run ON lineage_edges (run_id);

COMMENT ON TABLE lineage_edges IS 'lineage edges';
COMMENT ON COLUMN lineage_edges.edge_id IS 'edge id';
COMMENT ON COLUMN lineage_edges.source_type IS 'source type: JOB or DATASET';
COMMENT ON COLUMN lineage_edges.source_id IS 'source id';
COMMENT ON COLUMN lineage_edges.target_type IS 'target type: JOB or DATASET';
COMMENT ON COLUMN lineage_edges.target_id IS 'target id';
COMMENT ON COLUMN lineage_edges.edge_type IS 'edge type: INPUT or OUTPUT';
COMMENT ON COLUMN lineage_edges.run_id IS 'run id from OpenLineage event';
COMMENT ON COLUMN lineage_edges.created_at IS 'created timestamp';

-- Column-level lineage table
CREATE TABLE IF NOT EXISTS lineage_columns (
    column_lineage_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    source_dataset_id BIGINT NOT NULL,
    source_column VARCHAR(256) NOT NULL,
    target_dataset_id BIGINT NOT NULL,
    target_column VARCHAR(256) NOT NULL,
    transformation TEXT DEFAULT NULL,
    created_at BIGINT NOT NULL,
    PRIMARY KEY (column_lineage_id)
);

CREATE INDEX IF NOT EXISTS lineage_columns_idx_src ON lineage_columns (source_dataset_id, source_column);
CREATE INDEX IF NOT EXISTS lineage_columns_idx_tgt ON lineage_columns (target_dataset_id, target_column);

COMMENT ON TABLE lineage_columns IS 'column level lineage';
COMMENT ON COLUMN lineage_columns.column_lineage_id IS 'column lineage id';
COMMENT ON COLUMN lineage_columns.source_dataset_id IS 'source dataset id';
COMMENT ON COLUMN lineage_columns.source_column IS 'source column name';
COMMENT ON COLUMN lineage_columns.target_dataset_id IS 'target dataset id';
COMMENT ON COLUMN lineage_columns.target_column IS 'target column name';
COMMENT ON COLUMN lineage_columns.transformation IS 'transformation logic or expression';
COMMENT ON COLUMN lineage_columns.created_at IS 'created timestamp';
